### ISSUE TITLE
Several front-end page architectures

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroFrontEndDesign#9]
1. static layout 
2. float  layout 
3. fiex  layout 
4. gird layout

**Comment by macroldj** [comment]
static layout 
```md

```

**Comment by Macroldj** [comment]
float 再静态页面的基础之上再加上相关的左右浮动，给页面带来更多的可能性。

**Comment by Macroldj** [comment]
fiex 是更加适合与手机等等设备的盒子模型

**Comment by Macroldj** [comment]
grid 盒子模型，在页面操作的时候最基本的操作方式。
